### ISSUE TITLE
Xwiki 

### ISSUE THREAD

**Issue by HarshiniBV** [Vignana-Jyothi/web-ex#2]

**Comment by HarshiniBV** [comment]
//installation steps for xwiki:

- Package installed from:  **https://www.xwiki.org/xwiki/bin/view/Download/**  (stable).
- After installing XWiki package, run the following command in ubuntu: **sudo xwiki.start** 
- Then website is available in: **http://localhost:8080/xwiki/bin/view/Main/** (without running the following command this link will not work).
- Log-in or Sign-up into XWiki.
- To stop XWiki: **sudo xwiki.stop**

**Comment by HarshiniBV** [comment]
Features in XWIKI:
[https://www.xwiki.org/xwiki/bin/view/Documentation/UserGuide/Features/](url)

**Comment by head-iie-vnr** [comment]
This is a close match. 
Link the documentation


Thanks for doing this.
