### ISSUE TITLE
Tiki wiki install instructions

### ISSUE THREAD

**Issue by tarakakiranmayi** [Vignana-Jyothi/web-ex#4]
![Screenshot from 2024-05-14 21-26-49](https://github.com/Vignana-Jyothi/web-ex/assets/161358790/5b8ebff8-451d-4404-a849-e80ba448e6e9)
steps for  installation of tikiwiki:
1.sudo apt install apache2 mysql-server php libapache2-mod-php php-mysql(download php,mysql,apache2)
2.sudo apt install php-curl php-gd php-json php-xml php-mbstring php-zip php-xmlrpc(php extension)
3.create database:
sudo mysql -u root -p
CREATE DATABASE tikiwiki;
CREATE USER 'tikiuser'@'localhost' IDENTIFIED BY 'your_password';
GRANT ALL PRIVILEGES ON tikiwiki.* TO 'tikiuser'@'localhost';
FLUSH PRIVILEGES;
EXIT;
4.install tiki-27.0.alpha from https://sourceforge.net/projects/tikiwiki/files/latest/download
5.unzip tiki.zip -d /var/www/html/(add the zip extracted one to /var/www/html)
6.set permissions:
sudo chown -R www-data:www-data /var/www/html/tikiwiki/
sudo chmod -R 755 /var/www/html/tikiwiki/
7.sudo nano /etc/apache2/sites-available/tikiwiki.conf(open the file in text editor)
write the below code:
<VirtualHost *:80>
    ServerAdmin admin@example.com
    DocumentRoot /var/www/html/tikiwiki/
    ServerName your_domain.com
    ServerAlias www.your_domain.com

    <Directory /var/www/html/tikiwiki/>
        Options +FollowSymlinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
(ctrl+x+enter+cnrl+c=>to the save the file)
9.enable the site:sudo a2ensite tikiwiki.conf
sudo a2enmod rewrite
10.restart apache:sudo systemctl restart apache2

**Comment by tarakakiranmayi** [comment]
![Screenshot from 2024-05-14 21-54-52](https://github.com/Vignana-Jyothi/web-ex/assets/161358790/1b370649-fd51-4422-abf3-e67669115739)
this is after installation

**Comment by tarakakiranmayi** [comment]
![Screenshot from 2024-05-15 13-18-47](https://github.com/Vignana-Jyothi/web-ex/assets/161358790/88264092-b2b5-4114-81c4-d64706f57e40)
first page created

**Comment by head-iie-vnr** [comment]
Thanks for doing this.
