### ISSUE TITLE
Wiki.js Installation

### ISSUE THREAD

**Issue by DwarakaSivaSaiSriN** [Vignana-Jyothi/web-ex#5]
Wiki.js is an open-source documentation tool.
It has a very easy to understand Ui.
It is built on JavaScript.

**Comment by DwarakaSivaSaiSriN** [comment]
It is downloaded on docker.
The current stable version has requirements of NodeJS and a DB (PostgreSQL, MySQL, MariaDB, MSSQL or SQLite3)

I chose PostgreSQL as it is readily available on the system.

When downloading, it is recommended to choose one of the 'recommended guides' instead of 'By Platform' as it much easier than the later.

Steps to install locally on windows with support of docker: [LINK](https://docs.requarks.io/install/docker-desktop)

Step 1:
If docker is not yet installed on the system, it will provide a link to install on your OS.

Step 2: Create the Installation Folder.

**Comment by DwarakaSivaSaiSriN** [comment]
Steps to install locally with docker website.
--It is downloaded on PostgreSQL.

Step 1:
Install desktop docker 
Step 2:
At the desired place create a wiki folder and write the given PostgreSQL code
Step 3:
Open the wiki folder in command prompt and type 
docker compose up -d
Step 4:
Go to localhost:3000 to complete the installation

Note  It will ask for authentication

**Comment by head-iie-vnr** [comment]
![image](https://github.com/Vignana-Jyothi/web-ex/assets/163392003/578e0168-9450-4b40-9ded-a2715a2f055e)

**Comment by head-iie-vnr** [comment]
It supports page creation through various ways. 

draw.io diagrams can be added.

**Comment by DwarakaSivaSaiSriN** [comment]
Make sure the wiki.js is running in docker before opening the wiki.js page.

![Screenshot (40)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/21cf80f4-5c5f-454a-aa3b-8330de2b1548)

Note: To open the wiki.js type 'localhost' in the address bar

**Comment by DwarakaSivaSaiSriN** [comment]
Wiki.js Landing page:
![Screenshot (43)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/2b4ffb01-1bab-4359-b40a-825fb8acc9b9)

Administration: Will help you see and edit all the pages(documentation) created.
It will also allow to create teams to work on a documentation.

Another feature is that it will allow to assign a publishing date to forever (if needed).
![Screenshot (54)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/a6de786f-f42b-47bc-af33-110aea0f10c4)

**Comment by DwarakaSivaSaiSriN** [comment]
Create home page:
It gives multiple options to choose the kind of page you want.
![Uploading Screenshot (60).png…]()

**Comment by DwarakaSivaSaiSriN** [comment]
Mark down page :
![Screenshot (50)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/b7253226-d399-4d0c-a312-933aa4fb989d)

We can also draw diagrams using draw.io:
![Screenshot (55)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/a9b33873-cbab-4dd4-babd-49a3a97066db)

Note: Make sure JavaScript is enabled for your browser before accessing the draw.io application
![Screenshot (49)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/df2f841e-f8f5-41fe-9779-b0518dc9a0bf)

**Comment by DwarakaSivaSaiSriN** [comment]
Visual editor-
Adding Script:
![Screenshot (61)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/d46ec152-7f10-4d1d-8521-26f57a37eb44)
Adding css styles:
![Screenshot (62)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/ff9d15aa-6623-43a5-89b5-231f29575ca3)

The script and css styles make all the elements in the page to have the same styles as that applied in the above mentioned panel.
![Screenshot (63)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/c2176582-ae10-4ac7-8304-77404995b752)

**Comment by DwarakaSivaSaiSriN** [comment]
We can also convert a page into markdown, visual editor and a raw html page:
![Uploading Screenshot (56).png…]()

**Comment by DwarakaSivaSaiSriN** [comment]
We can also view the history of our edits.

**Comment by DwarakaSivaSaiSriN** [comment]
Major Drawbacks:
1. It incompletely supports multiple languages (still in development).
![Screenshot (67)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/fc9705af-829f-41f6-b5ac-edb541c369fa)
2. We can't view or edit the diagrams in visual editor mode properly which we had(can) only insert in markdown mode. We can't understand it at all in raw html mode.
![Screenshot (57)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/3c900f12-b3f0-4e6f-8ac4-9f67f340a231)

![Uploading Screenshot (58).png…]()

**Comment by DwarakaSivaSaiSriN** [comment]
But we can add images in visual editor by converting it into markdown.
Note: We can convert a page only to edit, after that it will go back to the view of initial choice.

**Comment by DwarakaSivaSaiSriN** [comment]
We can restrict comments (Allow or deny comments) for a page.

**Comment by DwarakaSivaSaiSriN** [comment]
**Embedding videos (Media Player):** While the current version of Wiki.js lacks support for embedding videos through a Media Player, the official documentation indicates that this feature may be introduced in future updates.

**Note:** Before updating the current version of wiki.js, one has to ensure that their data is save somewhere (say git) else their data may be lost.

**Comment by DwarakaSivaSaiSriN** [comment]
**To add embedded YouTube videos: **

![Screenshot (70)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/4c6fd44d-65a1-4418-8a56-97a015de2825)

- Make sure the above option is ENABLED!!!!!!

- Then continue to add the 'iframe' code to the markdown page.

![Screenshot (71)](https://github.com/Vignana-Jyothi/web-ex/assets/168963136/87f1a309-ba4c-4e90-a11b-c2338dff2c95)

**Comment by head-iie-vnr** [comment]
> Before updating the current version of wiki.js, one has to ensure that their data is saved somewhere (say git) else their data may be lost.

@DwarakaSivaSaiSriN 
Do you have instructions on how to take backup?  Should we create a new repo?  or our existing repo 'web-ex' is enough?

**Comment by head-iie-vnr** [comment]
@DwarakaSivaSaiSriN and @tarakakiranmayi 
Can we embed Twitter etc?   Can we integrate RSS feeds?

**Comment by DwarakaSivaSaiSriN** [comment]
> @DwarakaSivaSaiSriN and @tarakakiranmayi Can we embed Twitter etc? Can we integrate RSS feeds?

Yes sir, we can embed twitter.

**Comment by head-iie-vnr** [comment]
Thanks for doing this.
