### ISSUE TITLE
DETAILED VIEW AND FEATURES OF XWIKI

### ISSUE THREAD

**Issue by DEV-0912** [Vignana-Jyothi/web-ex#8]
![Screenshot from 2024-05-17 16-34-41](https://github.com/Vignana-Jyothi/web-ex/assets/169129783/aae1411b-2471-47ed-ae48-1f627fb80125)
![Screenshot from 2024-05-17 16-32-45](https://github.com/Vignana-Jyothi/web-ex/assets/169129783/b4d1a438-6204-4f9d-803c-07f54e59acc1)

**Comment by HarshiniBV** [comment]
https://docs.google.com/document/d/1mVO-PDflvmsOefFNjHS5yqRWxS7uSOeg0aMBd2HX6-Q/edit

**Comment by head-iie-vnr** [comment]
Thanks for the documentation @HarshiniBV  Great job.
