### ISSUE TITLE
Features of wiki.js

### ISSUE THREAD

**Issue by tarakakiranmayi** [Vignana-Jyothi/web-ex#9]
![IMG-20240518-WA0015](https://github.com/Vignana-Jyothi/web-ex/assets/161358790/e18ac8c0-573f-4fc5-8823-1aa5190c550e)
![IMG-20240518-WA0016](https://github.com/Vignana-Jyothi/web-ex/assets/161358790/004ec633-09fc-4801-8eef-01e8f12a6ac3)
![IMG-20240518-WA0017](https://github.com/Vignana-Jyothi/web-ex/assets/161358790/2da1a41b-b841-40fd-9a17-f8f75c5daef9)
![IMG-20240518-WA0021](https://github.com/Vignana-Jyothi/web-ex/assets/161358790/9c8979b7-421c-4de9-acc5-2a6686d72762)

**Comment by tarakakiranmayi** [comment]
https://docs.google.com/document/d/1Hdvm31996xd4_szSfB__lp_HWP1oMVAfj43FIeQ2KEw/edit?usp=sharing

**Comment by head-iie-vnr** [comment]
Great job @tarakakiranmayi @DwarakaSivaSaiSriN for doing this.
